### ISSUE TITLE
Unknown RTF command error, tried cmd$error

### ISSUE THREAD

**Issue by zxfrank** [iarna/rtf-parser#13]
I run into an issue and I'm trying to debug. Looks like stream_writable throw an error and the interpreter do not handle that.

more to come

**Comment by qimuxi1990** [comment]
In my case, this error shows up when I try to parse a plain text string as rtf string. And I got error saying 'empty control word'.

**Comment by qimuxi1990** [comment]
Also for continuous soft hyphen, example rtf string `{\\rtf1 \\-\\-` while `{\\rtf1 \\-` works fine.

**Comment by Programmerino** [comment]
I am also encountering a similar issue. Whenever `\-` is present in my RTF files, I get error:
```bash
Error: Error: empty control word
```
