### ISSUE TITLE
NULL terminated RTF file

### ISSUE THREAD

**Issue by rwolffgang** [iarna/rtf-parser#5]
I have a testfile generated by a Windows application, which is terminated by a NULL character. When I try to parse the file, I receive the following error message:

```
bundle.js:19429 Uncaught TypeError: Cannot read property 'addContent' of undefined
    at RTFInterpreter.cmd$text (bundle.js:19429)
    at RTFInterpreter._write (bundle.js:19382)
    at doWrite (bundle.js:18763)
    at writeOrBuffer (bundle.js:18752)
    at RTFInterpreter.Writable.write (bundle.js:18679)
    at RTFParser.ondata (bundle.js:17744)
    at RTFParser.EventEmitter.emit (bundle.js:22853)
    at addChunk (bundle.js:17416)
    at readableAddChunk (bundle.js:17403)
    at RTFParser.Readable.push (bundle.js:17370)
```

This is what the file looks like opened in a text editor.
```
{\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}}
{\colortbl ;\red128\green0\blue0;\red0\green0\blue0;}
{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\cf1\f0\fs20 Hello \cf2\ul\b\i World\ulnone\b0\i0\par
}<NUL>
```
I also [attached the file as TXT](https://github.com/iarna/rtf-parser/files/1572049/NULL.terminated.txt), since RTF is not supported by Github.

A simple workaround is to replace all NULL characters ahead of processing. But maybe there's a more elegant way to incorporate this into the library?

```
content = content.replace('\0', '');
parseRTF.string(content, (err, doc) => { ... });
```

Let me know if I can help any further.

**Comment by iarna** [comment]
Essentially the error is that it's getting a character outside of the RTF document, that is, outside of the `{\rtf1 }` group.

With the just landed patch to accept fragments, this now just produces a second grouping that gets added after the main one, with the null character in it. My gut feeling is that this case would be best served by `content.replace('\0$', '')`, that is, removing it ONLY if its a terminator. I dunno why you'd want nulls in your RTF anywhere else, but who am I to judge? =p
