### ISSUE TITLE
Failure when using a non-rtf string.

### ISSUE THREAD

**Issue by JaredCE** [iarna/rtf-parser#8]
I was looking for a RTF library that would do similar as to what the perl one does... came across yours.  Nice work, however, and perhaps i'm using it incorrectly, when i use this code:

```
const parseRTF = require("rtf-parser");
const fs = require('fs')

parseRTF.string('hi there', (err, doc) => {
console.log(err);
});
```
on runkit, i get an error, and not the expected err error.

TypeError: Cannot read property 'addContent' of null

either way, it probably shouldn't fail like that when using a non-rtf string?

**Comment by iarna** [comment]
Strictly speaking that's not valid RTF. Valid RTF opens with: `{\rtf1`  I can make it give a better error message, but what were you expecting it to do?

**Comment by iarna** [comment]
lol, ok, I didn't give you a chance to respond. XD I've made it accept plaintext like that and just treat it as if it were surrounded by `{\rtf1 }`, which means you can pass in fragments of RTF like `\i test\i0` to get a doc with `test` flagged as italic.
